FROM mhart/alpine-node:8.11.3

ENV NODE_PATH ./lib

RUN apk update && apk add \
    git \
    openssh-client

RUN yarn global add \
    nodemon

COPY package.json yarn.lock? .npmrc? /opt/app/

WORKDIR /opt/app

RUN yarn

COPY . /opt/app/

ENTRYPOINT ["nodemon", "./start.js"]

EXPOSE 8000