FROM mhart/alpine-node:8.11.3

ENV NODE_PATH ./lib

RUN apk update && apk add \
    git \
    openssh-client

RUN npm i -g nodemon

COPY package.json package-lock.json? .npmrc? /opt/app/

WORKDIR /opt/app

RUN npm i

COPY . /opt/app/

ENTRYPOINT ["nodemon", "./start.js"]

EXPOSE 8000